// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
[assembly: AssemblyTitle("ClothingLocker")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("ClothingLocker")]
[assembly: AssemblyCopyright("Copyright © asquared31415 2020")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyFileVersion("2020.4.3.30104")]
[assembly: AssemblyVersion("2020.4.3.30104")]
