// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyTitle("ShinebugReactor")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyProduct("ShinebugReactor")]
[assembly: AssemblyCopyright("Copyright © asquared31415 2020")]

[assembly: AssemblyVersion("2020.5.13.7961")]
