// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
[assembly: AssemblyTitle("BrothgarBroth")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("BrothgarBroth")]
[assembly: AssemblyCopyright("Copyright © asquared31415 2020")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyFileVersion("2020.4.9.38304")]
[assembly: AssemblyVersion("2020.4.9.38304")]
