// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyTitle( "Infinispeed" )]
[assembly: AssemblyDescription( "" )]
[assembly: AssemblyProduct( "Infinispeed" )]
[assembly: AssemblyCopyright( "Copyright © asquared31415 2020" )]

[assembly: AssemblyVersion( "2020.2.7.37895" )]
