// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyTitle( "ConfigurablePrintingPod" )]
[assembly: AssemblyDescription( "" )]
[assembly: AssemblyProduct( "ConfigurablePrintingPod" )]
[assembly: AssemblyCopyright( "Copyright © asquared31415 2020" )]

[assembly: AssemblyVersion( "2020.3.19.4893" )]
